{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable-hms",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "2.1.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.7.1.aar",
          "url": "notificare-scannable-hms-2.7.1.aar",
          "size": 22858,
          "sha512": "0893a5bf9218e3ea71673081890d0fb2991cd26ae8c8bbf3e7dedc8b09a1edb884f0b9c05b328f6c97a8c2d5855f10077b4614fec6f169300957a6688013aa54",
          "sha256": "6d90828ceb72f274daf447d6dbbe23d0cbe9ba9bbec62c71d42110fc0b642577",
          "sha1": "7f24fe2df6906a94a1bb25304c30a49b087ae200",
          "md5": "8f2d10a96b4aa13f7f62b676c026db7b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "2.1.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.7.1.aar",
          "url": "notificare-scannable-hms-2.7.1.aar",
          "size": 22858,
          "sha512": "0893a5bf9218e3ea71673081890d0fb2991cd26ae8c8bbf3e7dedc8b09a1edb884f0b9c05b328f6c97a8c2d5855f10077b4614fec6f169300957a6688013aa54",
          "sha256": "6d90828ceb72f274daf447d6dbbe23d0cbe9ba9bbec62c71d42110fc0b642577",
          "sha1": "7f24fe2df6906a94a1bb25304c30a49b087ae200",
          "md5": "8f2d10a96b4aa13f7f62b676c026db7b"
        }
      ]
    }
  ]
}
