{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.7.2.aar",
          "url": "notificare-billing-2.7.2.aar",
          "size": 28620,
          "sha512": "91d2862cb16e4637af2831bf1c642a112e0f3c7d9059d901ef02d71fabae21acc7affb3bb7145ff000490ccbc2aa70a5fbb4c7de91d7b39cff5f7e14acc9a2c1",
          "sha256": "6c36c6d029361f49f90bc45ccb04c55d96e87b682ab88904c92c5b99b86d8d12",
          "sha1": "9169b3f0e4ff7f43d8c5f98af5f7059b68392d3f",
          "md5": "fbf83f1e6b95fcd24b7e256d25e865d9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.7.2.aar",
          "url": "notificare-billing-2.7.2.aar",
          "size": 28620,
          "sha512": "91d2862cb16e4637af2831bf1c642a112e0f3c7d9059d901ef02d71fabae21acc7affb3bb7145ff000490ccbc2aa70a5fbb4c7de91d7b39cff5f7e14acc9a2c1",
          "sha256": "6c36c6d029361f49f90bc45ccb04c55d96e87b682ab88904c92c5b99b86d8d12",
          "sha1": "9169b3f0e4ff7f43d8c5f98af5f7059b68392d3f",
          "md5": "fbf83f1e6b95fcd24b7e256d25e865d9"
        }
      ]
    }
  ]
}
