{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location-hms",
    "version": "2.7.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "5.1.0.303"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.1.aar",
          "url": "notificare-location-hms-2.7.0-beta.1.aar",
          "size": 40143,
          "sha512": "61c044a083a4dfc15063cdce204c34fef027075f6314acd19f4f00e363258d739032b2e2688799878f1f58eb3e3a71bdce0a19189951a1a572efdf093841622a",
          "sha256": "95256bae9c796b08dfc19d70c503328c4670cc2323bba6f81ab93269d379c9cb",
          "sha1": "e636b30ac46729a738bbe15529bcea1529926919",
          "md5": "062028eb1836ffc19592c4f7a80bf209"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "5.1.0.303"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.1.aar",
          "url": "notificare-location-hms-2.7.0-beta.1.aar",
          "size": 40143,
          "sha512": "61c044a083a4dfc15063cdce204c34fef027075f6314acd19f4f00e363258d739032b2e2688799878f1f58eb3e3a71bdce0a19189951a1a572efdf093841622a",
          "sha256": "95256bae9c796b08dfc19d70c503328c4670cc2323bba6f81ab93269d379c9cb",
          "sha1": "e636b30ac46729a738bbe15529bcea1529926919",
          "md5": "062028eb1836ffc19592c4f7a80bf209"
        }
      ]
    }
  ]
}
