{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable-hms",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cvynx6tgmjgmnn2gjijnjoxnoy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.3.2.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.6.0.aar",
          "url": "notificare-scannable-hms-2.6.0.aar",
          "size": 22750,
          "sha512": "8843846ef0dba78e5e4eef761d080e07d1a372a768e0da3ddf8828aea9e38abf2c6d23ba918722eb34b5621c420ad6130260541ec13f773c58bf0bfc14493ed7",
          "sha256": "bf093bbff935d98affd78771e014810673e62d44137ab1cdaecd39830cb26d99",
          "sha1": "41170fbb9d89f142141d264efe0fa8f31aa04696",
          "md5": "278c4089323d8a01eec87f866982eff3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.3.2.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.6.0.aar",
          "url": "notificare-scannable-hms-2.6.0.aar",
          "size": 22750,
          "sha512": "8843846ef0dba78e5e4eef761d080e07d1a372a768e0da3ddf8828aea9e38abf2c6d23ba918722eb34b5621c420ad6130260541ec13f773c58bf0bfc14493ed7",
          "sha256": "bf093bbff935d98affd78771e014810673e62d44137ab1cdaecd39830cb26d99",
          "sha1": "41170fbb9d89f142141d264efe0fa8f31aa04696",
          "md5": "278c4089323d8a01eec87f866982eff3"
        }
      ]
    }
  ]
}
