{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-beacon",
    "version": "2.7.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19-beta2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-beacon-2.7.0-beta.1.aar",
          "url": "notificare-beacon-2.7.0-beta.1.aar",
          "size": 44894,
          "sha512": "4ac91872fbb58ef42850aeeda82610175b4902f5ad40dd60773c7fa3a0c07effb28d828a1161f0b9863e0a5698e174c3d06719b35ad2de6674ca03c3813eb5d0",
          "sha256": "8b646f4ddd54f46aaf3892511145929fee69d4e8689e0ec9fc6d9e47821697f9",
          "sha1": "4b2de6621e1d3484e94cd965ccc79434c0eb84ee",
          "md5": "cc465e826ae7ae6b1f9254e42ec0c12e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19-beta2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-beacon-2.7.0-beta.1.aar",
          "url": "notificare-beacon-2.7.0-beta.1.aar",
          "size": 44894,
          "sha512": "4ac91872fbb58ef42850aeeda82610175b4902f5ad40dd60773c7fa3a0c07effb28d828a1161f0b9863e0a5698e174c3d06719b35ad2de6674ca03c3813eb5d0",
          "sha256": "8b646f4ddd54f46aaf3892511145929fee69d4e8689e0ec9fc6d9e47821697f9",
          "sha1": "4b2de6621e1d3484e94cd965ccc79434c0eb84ee",
          "md5": "cc465e826ae7ae6b1f9254e42ec0c12e"
        }
      ]
    }
  ]
}
