{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-core",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cvynx6tgmjgmnn2gjijnjoxnoy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "18.0.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-2.6.0.aar",
          "url": "notificare-core-2.6.0.aar",
          "size": 33265,
          "sha512": "1cd09426478d274c2ccf14ae593f9654aa8360cf9d3ebee19f24f3e6676267afa4b1aeb4a3cd0ebce72976d04b2995ba74dd4055509557dba2262e5778de5f8b",
          "sha256": "1de0c36880b530bca08ec0a164cd826f77c0d63480ec61ac0c230573edcaef0b",
          "sha1": "85338e521779c2a1b89ebc0d4b32fafaec1f6f2e",
          "md5": "e12dce76a625edbd0489d38f8eedb0c5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "18.0.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-2.6.0.aar",
          "url": "notificare-core-2.6.0.aar",
          "size": 33265,
          "sha512": "1cd09426478d274c2ccf14ae593f9654aa8360cf9d3ebee19f24f3e6676267afa4b1aeb4a3cd0ebce72976d04b2995ba74dd4055509557dba2262e5778de5f8b",
          "sha256": "1de0c36880b530bca08ec0a164cd826f77c0d63480ec61ac0c230573edcaef0b",
          "sha1": "85338e521779c2a1b89ebc0d4b32fafaec1f6f2e",
          "md5": "e12dce76a625edbd0489d38f8eedb0c5"
        }
      ]
    }
  ]
}
