{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable-hms",
    "version": "2.4.0-beta-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "agdfvxiaw5elri7cxxfs2rhwdm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0-beta-3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.2.0.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.4.0-beta-3.aar",
          "url": "notificare-scannable-hms-2.4.0-beta-3.aar",
          "size": 22447,
          "sha512": "3f3057eb6496b2e3960ef001248f07d4903ae92c19aeb76d71082caf2e2e4d3ed145f692ff1965fe6ca237b1e1b26f594bd2058493f72a15ab796f7bab3b4e84",
          "sha256": "21349bc6f06d43a1de3020d5e4a2e05172368feff102594109e4000787784d64",
          "sha1": "29d00a8a5dcaaf681d5b3d23577bcd23f6f6d389",
          "md5": "9abd696dd417a37c7245e7cbad2e24c7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0-beta-3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.2.0.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.4.0-beta-3.aar",
          "url": "notificare-scannable-hms-2.4.0-beta-3.aar",
          "size": 22447,
          "sha512": "3f3057eb6496b2e3960ef001248f07d4903ae92c19aeb76d71082caf2e2e4d3ed145f692ff1965fe6ca237b1e1b26f594bd2058493f72a15ab796f7bab3b4e84",
          "sha256": "21349bc6f06d43a1de3020d5e4a2e05172368feff102594109e4000787784d64",
          "sha1": "29d00a8a5dcaaf681d5b3d23577bcd23f6f6d389",
          "md5": "9abd696dd417a37c7245e7cbad2e24c7"
        }
      ]
    }
  ]
}
