{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-core-hms",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xfqyhnzkqvbnlkaqbvm6qbtfeu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "5.0.3.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.5.1.aar",
          "url": "notificare-core-hms-2.5.1.aar",
          "size": 33600,
          "sha512": "d42ec70310906ea111434d0f6ea3051a479c8c1759e068328f52eee4f4cc72dc443fa4ac1bfceda70b2c5baa460a5ce909a078404c3fd254484eed4d2190d91f",
          "sha256": "7379307785ba4bcd75892a1527701b169092270e99b9a705a92c1f89f1a1bc58",
          "sha1": "f3f10905a83138ed61da23406403757e9668c037",
          "md5": "e63efe5296a361be6562892eff7573d7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "5.0.3.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.5.1.aar",
          "url": "notificare-core-hms-2.5.1.aar",
          "size": 33600,
          "sha512": "d42ec70310906ea111434d0f6ea3051a479c8c1759e068328f52eee4f4cc72dc443fa4ac1bfceda70b2c5baa460a5ce909a078404c3fd254484eed4d2190d91f",
          "sha256": "7379307785ba4bcd75892a1527701b169092270e99b9a705a92c1f89f1a1bc58",
          "sha1": "f3f10905a83138ed61da23406403757e9668c037",
          "md5": "e63efe5296a361be6562892eff7573d7"
        }
      ]
    }
  ]
}
