{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.4.0-beta-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "agdfvxiaw5elri7cxxfs2rhwdm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0-beta-3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.4.0-beta-3.aar",
          "url": "notificare-billing-2.4.0-beta-3.aar",
          "size": 27879,
          "sha512": "653d2174ebde4fd8e215395f9382fce67efe1b54bcecb876cb7d946101ef6d0f06f046b974eaed4b40805424b2b5552e51c56989503ef7a176198b9c53e5d007",
          "sha256": "a9a7319a0e7e701e3b8c3205ffa38121e7bd0b202dc7218ebe4b6d60b260d403",
          "sha1": "d62774285b71085c1f2bfdb69e5c2cbf84246560",
          "md5": "8bd2336365936f4d3e6afe2b21e988c1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0-beta-3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.4.0-beta-3.aar",
          "url": "notificare-billing-2.4.0-beta-3.aar",
          "size": 27879,
          "sha512": "653d2174ebde4fd8e215395f9382fce67efe1b54bcecb876cb7d946101ef6d0f06f046b974eaed4b40805424b2b5552e51c56989503ef7a176198b9c53e5d007",
          "sha256": "a9a7319a0e7e701e3b8c3205ffa38121e7bd0b202dc7218ebe4b6d60b260d403",
          "sha1": "d62774285b71085c1f2bfdb69e5c2cbf84246560",
          "md5": "8bd2336365936f4d3e6afe2b21e988c1"
        }
      ]
    }
  ]
}
