{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-core-hms",
    "version": "2.7.0-beta.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.6"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "6.1.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "6.0.1.304"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.7.0-beta.6.aar",
          "url": "notificare-core-hms-2.7.0-beta.6.aar",
          "size": 33707,
          "sha512": "34e2b93a379bf67be0cd378348ef350889df6a0ad1c814204d03d5a1237faf70c741559cd27d2626ae3b7bf1d85b6573ae846367aa8773ec380f0d33c1fd4484",
          "sha256": "4a0ac588d347dbf3b1630eaa02d8e3028d4fa45d665bddb905bde79588f19da5",
          "sha1": "9efe127206eb16abb88286b0cf6fd61bc67c93c5",
          "md5": "905902c8831f2f32a05f4269c567b7e1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.6"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "6.1.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "6.0.1.304"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.7.0-beta.6.aar",
          "url": "notificare-core-hms-2.7.0-beta.6.aar",
          "size": 33707,
          "sha512": "34e2b93a379bf67be0cd378348ef350889df6a0ad1c814204d03d5a1237faf70c741559cd27d2626ae3b7bf1d85b6573ae846367aa8773ec380f0d33c1fd4484",
          "sha256": "4a0ac588d347dbf3b1630eaa02d8e3028d4fa45d665bddb905bde79588f19da5",
          "sha1": "9efe127206eb16abb88286b0cf6fd61bc67c93c5",
          "md5": "905902c8831f2f32a05f4269c567b7e1"
        }
      ]
    }
  ]
}
