{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-beacon",
    "version": "2.7.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19-beta5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-beacon-2.7.0-beta.3.aar",
          "url": "notificare-beacon-2.7.0-beta.3.aar",
          "size": 44904,
          "sha512": "11b7696564423956cd455ab64592eb846bd69251d26cbee3f401afa8b60401155d0b7a31ec859f7787a8e3a87e9f83b26c4ebe819995c66372be2a6cfb351312",
          "sha256": "3cc5e8ada9c41ab5bf3ddc0f79c50967426581f31bb741456e46c74f4eee31f2",
          "sha1": "a4031eb36502a91e42d5d5abfa99395ec432a679",
          "md5": "79f7c44a1c1bab43f5e48d3ccafa4731"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19-beta5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-beacon-2.7.0-beta.3.aar",
          "url": "notificare-beacon-2.7.0-beta.3.aar",
          "size": 44904,
          "sha512": "11b7696564423956cd455ab64592eb846bd69251d26cbee3f401afa8b60401155d0b7a31ec859f7787a8e3a87e9f83b26c4ebe819995c66372be2a6cfb351312",
          "sha256": "3cc5e8ada9c41ab5bf3ddc0f79c50967426581f31bb741456e46c74f4eee31f2",
          "sha1": "a4031eb36502a91e42d5d5abfa99395ec432a679",
          "md5": "79f7c44a1c1bab43f5e48d3ccafa4731"
        }
      ]
    }
  ]
}
