{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-support-lib-android",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "notificare-support-lib-android-2.2.0.aar",
          "url": "notificare-support-lib-android-2.2.0.aar",
          "size": 49407,
          "sha512": "6c490c80dd386c47b12370194b8c2b0af09619634275648bb7cb5541e6cdbe03df60e96e15e668f16e94aab5eb997cdbf11ba0f1aa5ea502a684a664293949ce",
          "sha256": "b0e03def19a217816826be77e7c80c694e7ce0d28c9874a5fe1b5a4b402891de",
          "sha1": "5b3a5f8e8391e6e723ae9dfe7050229a8bc2565d",
          "md5": "b02a8ff12e74908fb41c59728d46c9af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "notificare-support-lib-android-2.2.0.aar",
          "url": "notificare-support-lib-android-2.2.0.aar",
          "size": 49407,
          "sha512": "6c490c80dd386c47b12370194b8c2b0af09619634275648bb7cb5541e6cdbe03df60e96e15e668f16e94aab5eb997cdbf11ba0f1aa5ea502a684a664293949ce",
          "sha256": "b0e03def19a217816826be77e7c80c694e7ce0d28c9874a5fe1b5a4b402891de",
          "sha1": "5b3a5f8e8391e6e723ae9dfe7050229a8bc2565d",
          "md5": "b02a8ff12e74908fb41c59728d46c9af"
        }
      ]
    }
  ]
}
