{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-support-lib-android",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "notificare-support-lib-android-2.2.0.aar",
          "url": "notificare-support-lib-android-2.2.0.aar",
          "size": 49403,
          "sha512": "1d9c349a87e47783809a445e6c74461efd502ef830a24d925b7e0cdf2a7dd7f9d9dd96c8181e1800c7dcb6e47ae749b925b3533755d52c3f1eff4d0b8f0c45a1",
          "sha256": "4bc93ea7494127a01369103ade89e34d60f86f60d67c3957da6d0d4a0e8c02a6",
          "sha1": "923f7b975484a1f8bd0ae6d348ec666b881f61c2",
          "md5": "12e944f42c7a3dd0d0428705516ead6f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "notificare-support-lib-android-2.2.0.aar",
          "url": "notificare-support-lib-android-2.2.0.aar",
          "size": 49403,
          "sha512": "1d9c349a87e47783809a445e6c74461efd502ef830a24d925b7e0cdf2a7dd7f9d9dd96c8181e1800c7dcb6e47ae749b925b3533755d52c3f1eff4d0b8f0c45a1",
          "sha256": "4bc93ea7494127a01369103ade89e34d60f86f60d67c3957da6d0d4a0e8c02a6",
          "sha1": "923f7b975484a1f8bd0ae6d348ec666b881f61c2",
          "md5": "12e944f42c7a3dd0d0428705516ead6f"
        }
      ]
    }
  ]
}
