{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tl6fgpxoobgrhlc3nbw73xkema"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.4.0.aar",
          "url": "notificare-billing-2.4.0.aar",
          "size": 27884,
          "sha512": "49d56d925f8a1b4f4912f83fb2279f9f5076b41ba9bbdacc092452a0ae96dfd4509d23b8ff126dfa0fdd200b696813932e594c5a8e54d92e12153b0fd3d67075",
          "sha256": "ea73d61aa9aa7bfa32ffc4d89839347fa1e97cb47511b9d2ffd72812f9dfa84a",
          "sha1": "fee46142b66f1983b06b8bf6bb12c74d98e9bdf3",
          "md5": "c870cf1b104cabaa274117f39d0f3109"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.4.0.aar",
          "url": "notificare-billing-2.4.0.aar",
          "size": 27884,
          "sha512": "49d56d925f8a1b4f4912f83fb2279f9f5076b41ba9bbdacc092452a0ae96dfd4509d23b8ff126dfa0fdd200b696813932e594c5a8e54d92e12153b0fd3d67075",
          "sha256": "ea73d61aa9aa7bfa32ffc4d89839347fa1e97cb47511b9d2ffd72812f9dfa84a",
          "sha1": "fee46142b66f1983b06b8bf6bb12c74d98e9bdf3",
          "md5": "c870cf1b104cabaa274117f39d0f3109"
        }
      ]
    }
  ]
}
