{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable-hms",
    "version": "2.7.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "2.0.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.7.0-beta.3.aar",
          "url": "notificare-scannable-hms-2.7.0-beta.3.aar",
          "size": 22856,
          "sha512": "037fde5b5e9b79539a9d958573665af4202a7ad75ed837b643d667befec1cc4385c64856c97d1634c140194bbe04de5362d1e7679058792e018c9247b08a1b89",
          "sha256": "ef6c44ff6b38b5f29857c0805d33869c8afd4a35c4c48cc50bb13e7e15ea4bbb",
          "sha1": "b09ed51a5bf0f545a3b3a4bd0a41bbc76d59db14",
          "md5": "7994eb58c2a5325683af018080d0e58b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "2.0.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.7.0-beta.3.aar",
          "url": "notificare-scannable-hms-2.7.0-beta.3.aar",
          "size": 22856,
          "sha512": "037fde5b5e9b79539a9d958573665af4202a7ad75ed837b643d667befec1cc4385c64856c97d1634c140194bbe04de5362d1e7679058792e018c9247b08a1b89",
          "sha256": "ef6c44ff6b38b5f29857c0805d33869c8afd4a35c4c48cc50bb13e7e15ea4bbb",
          "sha1": "b09ed51a5bf0f545a3b3a4bd0a41bbc76d59db14",
          "md5": "7994eb58c2a5325683af018080d0e58b"
        }
      ]
    }
  ]
}
