{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location-hms",
    "version": "2.7.0-beta.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "5.1.0.303"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.2.aar",
          "url": "notificare-location-hms-2.7.0-beta.2.aar",
          "size": 40155,
          "sha512": "d5e109c85d7e7828b9c7c7f2956d3b98fd5e5f582cc32decc01eb775c33bced19b2380a600a51704722db7f3b6cae9254d85275cc2eb5810e490b158b3164cfd",
          "sha256": "8a679f82c25d2ab982a032c9f134c0d9d03647cb33cc27947597b13ee9d8ff55",
          "sha1": "5d360da22b27c42cc837b0302b48fd478e422b1a",
          "md5": "6cdc486799ddd5d170028f700d477267"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "5.1.0.303"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.2.aar",
          "url": "notificare-location-hms-2.7.0-beta.2.aar",
          "size": 40155,
          "sha512": "d5e109c85d7e7828b9c7c7f2956d3b98fd5e5f582cc32decc01eb775c33bced19b2380a600a51704722db7f3b6cae9254d85275cc2eb5810e490b158b3164cfd",
          "sha256": "8a679f82c25d2ab982a032c9f134c0d9d03647cb33cc27947597b13ee9d8ff55",
          "sha1": "5d360da22b27c42cc837b0302b48fd478e422b1a",
          "md5": "6cdc486799ddd5d170028f700d477267"
        }
      ]
    }
  ]
}
