{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.7.3.aar",
          "url": "notificare-billing-2.7.3.aar",
          "size": 28644,
          "sha512": "ad63f655ca05ac3f73318fa227a1d515c7500a894d523ce89b90970d49e79460340481f40da44a4a887d34970675eb7c3520c07e87f8706a70c3d76b74b01320",
          "sha256": "f9312080dcd5a358d50f93a4deca68b67acd0dd208d0844edb1b01c1c2c5380e",
          "sha1": "2e4cf82063f9aeca939b38b18d61797c1bc6e1e6",
          "md5": "9d361d615d4f8f90e9ccd262359442fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.7.3.aar",
          "url": "notificare-billing-2.7.3.aar",
          "size": 28644,
          "sha512": "ad63f655ca05ac3f73318fa227a1d515c7500a894d523ce89b90970d49e79460340481f40da44a4a887d34970675eb7c3520c07e87f8706a70c3d76b74b01320",
          "sha256": "f9312080dcd5a358d50f93a4deca68b67acd0dd208d0844edb1b01c1c2c5380e",
          "sha1": "2e4cf82063f9aeca939b38b18d61797c1bc6e1e6",
          "md5": "9d361d615d4f8f90e9ccd262359442fd"
        }
      ]
    }
  ]
}
