{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location-hms",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.4"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "6.3.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.4.aar",
          "url": "notificare-location-hms-2.7.4.aar",
          "size": 40504,
          "sha512": "f925cd0912e1c45a2fb8413f941d2e732d7f17186bf45ae83e20eea3d2e892f0017a039fb5ba4def1deecf728311a9279275ac99cbabb82cc5d4645ccecd1877",
          "sha256": "c6ba4cf13df69e8487bdf7feab5180bd92678e6ee52871ffe95f705deb72bc1c",
          "sha1": "374dac69559b828e595e93d8ac1ea88dd617529c",
          "md5": "1ed9ab8d5a6ec0c99f5170318ced0f31"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.4"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "6.3.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.4.aar",
          "url": "notificare-location-hms-2.7.4.aar",
          "size": 40504,
          "sha512": "f925cd0912e1c45a2fb8413f941d2e732d7f17186bf45ae83e20eea3d2e892f0017a039fb5ba4def1deecf728311a9279275ac99cbabb82cc5d4645ccecd1877",
          "sha256": "c6ba4cf13df69e8487bdf7feab5180bd92678e6ee52871ffe95f705deb72bc1c",
          "sha1": "374dac69559b828e595e93d8ac1ea88dd617529c",
          "md5": "1ed9ab8d5a6ec0c99f5170318ced0f31"
        }
      ]
    }
  ]
}
