{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location-hms",
    "version": "2.7.0-beta.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "6.0.0.302"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.5.aar",
          "url": "notificare-location-hms-2.7.0-beta.5.aar",
          "size": 40330,
          "sha512": "2eb76e909f0b7a8b11f2aed55f19917c3d811c7858b1caf2e6642fa4387603fb69045c7f4262f7601f28fd10236e4b3db6f0c6b436985e09772ee0d3064e06e4",
          "sha256": "cc869fc945ec576cc8f7134411efd882dc75ee03c7fbc1b9eb1a4981156749a4",
          "sha1": "dba236ecb9e9889e835d5c4162b1d6ff01b34535",
          "md5": "dad3ee61cbfaa5ad3c88cc7fe7a5171e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "6.0.0.302"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.5.aar",
          "url": "notificare-location-hms-2.7.0-beta.5.aar",
          "size": 40330,
          "sha512": "2eb76e909f0b7a8b11f2aed55f19917c3d811c7858b1caf2e6642fa4387603fb69045c7f4262f7601f28fd10236e4b3db6f0c6b436985e09772ee0d3064e06e4",
          "sha256": "cc869fc945ec576cc8f7134411efd882dc75ee03c7fbc1b9eb1a4981156749a4",
          "sha1": "dba236ecb9e9889e835d5c4162b1d6ff01b34535",
          "md5": "dad3ee61cbfaa5ad3c88cc7fe7a5171e"
        }
      ]
    }
  ]
}
