{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location",
    "version": "2.5.0-beta-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ronk5dkspvavpkha437asd23qe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.0-beta-1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-2.5.0-beta-1.aar",
          "url": "notificare-location-2.5.0-beta-1.aar",
          "size": 40085,
          "sha512": "e85059fc5437c12a5ac25e873e3ec9d19bc3f8e7ce19c7246b040f579104b8a289ff0ee822e76793d384114c00b220b1ac57644fa2d75050683fa132edd2719f",
          "sha256": "4ea1b899a389c220e1b7ee3e8bd011a8a821e519568ea4639d8d7ede1a6c87b4",
          "sha1": "0ee309c018a3efb7573e9c622d98b868b213cbf3",
          "md5": "cd53c79b5e40c8edef8b3e6f1e8b4c4e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.0-beta-1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-2.5.0-beta-1.aar",
          "url": "notificare-location-2.5.0-beta-1.aar",
          "size": 40085,
          "sha512": "e85059fc5437c12a5ac25e873e3ec9d19bc3f8e7ce19c7246b040f579104b8a289ff0ee822e76793d384114c00b220b1ac57644fa2d75050683fa132edd2719f",
          "sha256": "4ea1b899a389c220e1b7ee3e8bd011a8a821e519568ea4639d8d7ede1a6c87b4",
          "sha1": "0ee309c018a3efb7573e9c622d98b868b213cbf3",
          "md5": "cd53c79b5e40c8edef8b3e6f1e8b4c4e"
        }
      ]
    }
  ]
}
