{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "57plzex2infsxhos2oulpqbh3q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.4.1.aar",
          "url": "notificare-billing-2.4.1.aar",
          "size": 27886,
          "sha512": "e5480cde3c0f2c291181b46771e7ca0a60c7d5fb0f99c85c8ccde592204a0dbb4a10ded2618a11e6e76b4d6c841097c6f7974bbce8226e7fbef1c98d13e4447f",
          "sha256": "ed9be0320bf97fc15af91f3b5aec6ac9e50f68b41a746929c2307f542009e607",
          "sha1": "74a003ff17f9ccf4fb9c3ea84972335928f1ed12",
          "md5": "26d2356690924c31c2e8d40bcb1686be"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.4.1.aar",
          "url": "notificare-billing-2.4.1.aar",
          "size": 27886,
          "sha512": "e5480cde3c0f2c291181b46771e7ca0a60c7d5fb0f99c85c8ccde592204a0dbb4a10ded2618a11e6e76b4d6c841097c6f7974bbce8226e7fbef1c98d13e4447f",
          "sha256": "ed9be0320bf97fc15af91f3b5aec6ac9e50f68b41a746929c2307f542009e607",
          "sha1": "74a003ff17f9ccf4fb9c3ea84972335928f1ed12",
          "md5": "26d2356690924c31c2e8d40bcb1686be"
        }
      ]
    }
  ]
}
