{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xfqyhnzkqvbnlkaqbvm6qbtfeu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-2.5.1.aar",
          "url": "notificare-location-2.5.1.aar",
          "size": 40150,
          "sha512": "3e22b444dd57ada44591e37bfe239ee5f842be9aee0653e285be4135e4747e405a51fa156258afdc85e1ce743978fe5416bc37ddf095988fd05e03c68be79549",
          "sha256": "7c5a53fab15355805295e7be8df529c05f1ae11e0d1fb4969896408ffe238155",
          "sha1": "0f5b40734b9e2255b5d5823b19cba857198034c2",
          "md5": "bc0b48e682c4fe85af27ec5c0eefd061"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-2.5.1.aar",
          "url": "notificare-location-2.5.1.aar",
          "size": 40150,
          "sha512": "3e22b444dd57ada44591e37bfe239ee5f842be9aee0653e285be4135e4747e405a51fa156258afdc85e1ce743978fe5416bc37ddf095988fd05e03c68be79549",
          "sha256": "7c5a53fab15355805295e7be8df529c05f1ae11e0d1fb4969896408ffe238155",
          "sha1": "0f5b40734b9e2255b5d5823b19cba857198034c2",
          "md5": "bc0b48e682c4fe85af27ec5c0eefd061"
        }
      ]
    }
  ]
}
