{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-beacon",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.4"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19.4"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-beacon-2.7.4.aar",
          "url": "notificare-beacon-2.7.4.aar",
          "size": 24801,
          "sha512": "b26002f2112fe5d88595230c177e3fc453e280f402bd430dfeada98fde57b97cebfe76984853c36a91b9a162cee5fca6d9fd6c6d215a6944290b5c6888e53fa1",
          "sha256": "3bfa6458d250be4c96cfcd2c13a628ca7be186df468dbbaf18e73e7457315916",
          "sha1": "3226784caf97ddf33dc7b4faf3fb77840d44612f",
          "md5": "73f18cce6cabe939bb7de7d788fd96cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.4"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19.4"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-beacon-2.7.4.aar",
          "url": "notificare-beacon-2.7.4.aar",
          "size": 24801,
          "sha512": "b26002f2112fe5d88595230c177e3fc453e280f402bd430dfeada98fde57b97cebfe76984853c36a91b9a162cee5fca6d9fd6c6d215a6944290b5c6888e53fa1",
          "sha256": "3bfa6458d250be4c96cfcd2c13a628ca7be186df468dbbaf18e73e7457315916",
          "sha1": "3226784caf97ddf33dc7b4faf3fb77840d44612f",
          "md5": "73f18cce6cabe939bb7de7d788fd96cb"
        }
      ]
    }
  ]
}
