{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cvynx6tgmjgmnn2gjijnjoxnoy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision",
          "version": {
            "requires": "20.1.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-2.6.0.aar",
          "url": "notificare-scannable-2.6.0.aar",
          "size": 24360,
          "sha512": "d0834a4a6bfdd9a0e76cb26b209ce2dde85e7452630b31bc4bbf54466ada84a2c01195693e2ee99b10626837e0795dcdfe819d605f21eaf9173d9c7c4532d060",
          "sha256": "f5f6c120dbb1ed724292d47cdbe2b7ed692ccb1f1c7b62fb15a31f5f90c26f66",
          "sha1": "fe18c5c03fb216a322b973a4f9925c47b7e2971a",
          "md5": "30f7096dbc57ce37f539c164edadf3b8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision",
          "version": {
            "requires": "20.1.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-2.6.0.aar",
          "url": "notificare-scannable-2.6.0.aar",
          "size": 24360,
          "sha512": "d0834a4a6bfdd9a0e76cb26b209ce2dde85e7452630b31bc4bbf54466ada84a2c01195693e2ee99b10626837e0795dcdfe819d605f21eaf9173d9c7c4532d060",
          "sha256": "f5f6c120dbb1ed724292d47cdbe2b7ed692ccb1f1c7b62fb15a31f5f90c26f66",
          "sha1": "fe18c5c03fb216a322b973a4f9925c47b7e2971a",
          "md5": "30f7096dbc57ce37f539c164edadf3b8"
        }
      ]
    }
  ]
}
