{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location-hms",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "57plzex2infsxhos2oulpqbh3q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "5.0.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.4.1.aar",
          "url": "notificare-location-hms-2.4.1.aar",
          "size": 37647,
          "sha512": "1674d5ac63bfca8afd28c48d17a70b98ec9dfd7eb29f138515d54febf0df957fc3c211beda21ba95be93326800673e0e852e875725bbb8253d3b86031e4f799e",
          "sha256": "283fba5be213906991af67bd6ade4012d750b4f696ec0ae43ba77205e6e1d289",
          "sha1": "d28801d7efea183250638c4419c4c32826116016",
          "md5": "e349209a2ba78d3211194069f084de48"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "5.0.0.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.4.1.aar",
          "url": "notificare-location-hms-2.4.1.aar",
          "size": 37647,
          "sha512": "1674d5ac63bfca8afd28c48d17a70b98ec9dfd7eb29f138515d54febf0df957fc3c211beda21ba95be93326800673e0e852e875725bbb8253d3b86031e4f799e",
          "sha256": "283fba5be213906991af67bd6ade4012d750b4f696ec0ae43ba77205e6e1d289",
          "sha1": "d28801d7efea183250638c4419c4c32826116016",
          "md5": "e349209a2ba78d3211194069f084de48"
        }
      ]
    }
  ]
}
