{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable-hms",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lt3usfttqrfkxox2o3btruushq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.2.4.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.4.2.aar",
          "url": "notificare-scannable-hms-2.4.2.aar",
          "size": 22575,
          "sha512": "a5b32b0989cc8dd1a7444d060e53f624a53e54473f3d8656b6b8af8c0a0b29b0153f665fb468c0e42cdb1427fcf4d3e85f62ece9287e7b42f0a788056be7e4c3",
          "sha256": "4f4699fd2d48d66a5e960ddd25f23f08b86f6bb8ed0a87274c7b564b886afead",
          "sha1": "05269c151f50bb8b6b4d52b60bc05e22d9b93ceb",
          "md5": "d4ede774aefac162ac050313a96c6050"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.2.4.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.4.2.aar",
          "url": "notificare-scannable-hms-2.4.2.aar",
          "size": 22575,
          "sha512": "a5b32b0989cc8dd1a7444d060e53f624a53e54473f3d8656b6b8af8c0a0b29b0153f665fb468c0e42cdb1427fcf4d3e85f62ece9287e7b42f0a788056be7e4c3",
          "sha256": "4f4699fd2d48d66a5e960ddd25f23f08b86f6bb8ed0a87274c7b564b886afead",
          "sha1": "05269c151f50bb8b6b4d52b60bc05e22d9b93ceb",
          "md5": "d4ede774aefac162ac050313a96c6050"
        }
      ]
    }
  ]
}
