{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-core-hms",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cvynx6tgmjgmnn2gjijnjoxnoy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "5.1.1.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "5.2.0.302"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.6.0.aar",
          "url": "notificare-core-hms-2.6.0.aar",
          "size": 33591,
          "sha512": "3b97466e3c07a5c4b024bda82abfffd4cd4d054200b397d6123de01cd06d4f34214f934320a6e1f9220608db27c8b91bc0fd26d1a12f59e1cd173876a43d3381",
          "sha256": "468c06a7e00717ad5977fe472f287dd0e1ce847e916b2299a0c20d2d4cb94a7f",
          "sha1": "eae1f65a69f8850be57292e7b788d2039ec1e06d",
          "md5": "14dc6a6e7c0f8fe3132e58ce90b1397d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.6.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "5.1.1.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "5.2.0.302"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.6.0.aar",
          "url": "notificare-core-hms-2.6.0.aar",
          "size": 33591,
          "sha512": "3b97466e3c07a5c4b024bda82abfffd4cd4d054200b397d6123de01cd06d4f34214f934320a6e1f9220608db27c8b91bc0fd26d1a12f59e1cd173876a43d3381",
          "sha256": "468c06a7e00717ad5977fe472f287dd0e1ce847e916b2299a0c20d2d4cb94a7f",
          "sha1": "eae1f65a69f8850be57292e7b788d2039ec1e06d",
          "md5": "14dc6a6e7c0f8fe3132e58ce90b1397d"
        }
      ]
    }
  ]
}
