{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xfqyhnzkqvbnlkaqbvm6qbtfeu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.5.1.aar",
          "url": "notificare-billing-2.5.1.aar",
          "size": 28189,
          "sha512": "f6f71fba639f09381c01654c3d0ff3aaf29878f95d3cf8e3e030fda13dce1212f6778029380bfb8eb57e0a5d5b077781f196e33da6e44bfd70a93905e1c354b1",
          "sha256": "3ae4f78a892ae2bf667fed5aa43edd9691e70abc586bc2e38ff9ac804bc20c00",
          "sha1": "90e8362a7a89595c76f99e990ff37aee36e530b8",
          "md5": "4ba3ee59ba07686342e2e59ff6398e5d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.5.1.aar",
          "url": "notificare-billing-2.5.1.aar",
          "size": 28189,
          "sha512": "f6f71fba639f09381c01654c3d0ff3aaf29878f95d3cf8e3e030fda13dce1212f6778029380bfb8eb57e0a5d5b077781f196e33da6e44bfd70a93905e1c354b1",
          "sha256": "3ae4f78a892ae2bf667fed5aa43edd9691e70abc586bc2e38ff9ac804bc20c00",
          "sha1": "90e8362a7a89595c76f99e990ff37aee36e530b8",
          "md5": "4ba3ee59ba07686342e2e59ff6398e5d"
        }
      ]
    }
  ]
}
