{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-common",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tl6fgpxoobgrhlc3nbw73xkema"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.http-client",
          "module": "google-http-client-jackson2",
          "version": {
            "requires": "1.24.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.oauth-client",
          "module": "google-oauth-client",
          "version": {
            "requires": "1.24.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-common-2.4.0.aar",
          "url": "notificare-common-2.4.0.aar",
          "size": 662965,
          "sha512": "999629da3e4bf1b3276ae9a91b0119f245802b9c4d274a2979061d500ad5f09d99971368a36d769f7228a58557380a011004bc97cc505ab640898a3c6492ed9e",
          "sha256": "0db472ff2602eeefa0f50be894f36f3098b791c0eaaea126b322b59aeb39a597",
          "sha1": "cd85a5b902b9a9826c3f03e41accc34cb0aebf93",
          "md5": "9a189b3f8b3729cfafbee03ecd1f92b2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.http-client",
          "module": "google-http-client-jackson2",
          "version": {
            "requires": "1.24.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.oauth-client",
          "module": "google-oauth-client",
          "version": {
            "requires": "1.24.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-common-2.4.0.aar",
          "url": "notificare-common-2.4.0.aar",
          "size": 662965,
          "sha512": "999629da3e4bf1b3276ae9a91b0119f245802b9c4d274a2979061d500ad5f09d99971368a36d769f7228a58557380a011004bc97cc505ab640898a3c6492ed9e",
          "sha256": "0db472ff2602eeefa0f50be894f36f3098b791c0eaaea126b322b59aeb39a597",
          "sha1": "cd85a5b902b9a9826c3f03e41accc34cb0aebf93",
          "md5": "9a189b3f8b3729cfafbee03ecd1f92b2"
        }
      ]
    }
  ]
}
