{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-location-hms",
    "version": "2.7.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "6.0.0.302"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.3.aar",
          "url": "notificare-location-hms-2.7.0-beta.3.aar",
          "size": 40327,
          "sha512": "871d2af986864dfe29a93cd40cc839eaa02b77be163eccc740cab9a6a9a0f700072e2f904d04f3fa95c1ab82c768d45810735edf33a4f827ab04be9ac59487ad",
          "sha256": "5a7fadfbaf7bc28d314f27d27c1d241f00655aa0c842bf60e3d0462c490fdc60",
          "sha1": "d01d4cefa4bd6d8eb7de3f6f26c0e3acf7ff107c",
          "md5": "f532d772c429851ed4956906d9a91525"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "location",
          "version": {
            "requires": "6.0.0.302"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-location-hms-2.7.0-beta.3.aar",
          "url": "notificare-location-hms-2.7.0-beta.3.aar",
          "size": 40327,
          "sha512": "871d2af986864dfe29a93cd40cc839eaa02b77be163eccc740cab9a6a9a0f700072e2f904d04f3fa95c1ab82c768d45810735edf33a4f827ab04be9ac59487ad",
          "sha256": "5a7fadfbaf7bc28d314f27d27c1d241f00655aa0c842bf60e3d0462c490fdc60",
          "sha1": "d01d4cefa4bd6d8eb7de3f6f26c0e3acf7ff107c",
          "md5": "f532d772c429851ed4956906d9a91525"
        }
      ]
    }
  ]
}
