{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable-hms",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tl6fgpxoobgrhlc3nbw73xkema"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.2.0.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.4.0.aar",
          "url": "notificare-scannable-hms-2.4.0.aar",
          "size": 22451,
          "sha512": "957dda744a7e15ac1c55c6b9c4fa172fbbb0c4abc87d1853c04a872e82e89716095f8469e55afa4bd49d0274e51a0c6fe3c031c00ea1e7fa110d78e87084d7fa",
          "sha256": "edc5759bebc24f4a9e72be278dd1ba334602acb945f4594a41fa5c3748e3b305",
          "sha1": "6dd2401abc7f80ace46a5ded2de1adf1c149710e",
          "md5": "30338c67ae09e00977cd7e5514bbb60e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "scan",
          "version": {
            "requires": "1.2.0.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-hms-2.4.0.aar",
          "url": "notificare-scannable-hms-2.4.0.aar",
          "size": 22451,
          "sha512": "957dda744a7e15ac1c55c6b9c4fa172fbbb0c4abc87d1853c04a872e82e89716095f8469e55afa4bd49d0274e51a0c6fe3c031c00ea1e7fa110d78e87084d7fa",
          "sha256": "edc5759bebc24f4a9e72be278dd1ba334602acb945f4594a41fa5c3748e3b305",
          "sha1": "6dd2401abc7f80ace46a5ded2de1adf1c149710e",
          "md5": "30338c67ae09e00977cd7e5514bbb60e"
        }
      ]
    }
  ]
}
