{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-billing",
    "version": "2.7.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-alpha04"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.7.0-beta.3.aar",
          "url": "notificare-billing-2.7.0-beta.3.aar",
          "size": 28572,
          "sha512": "256657b1a9f6b1aca7e367ee481169ca595e41b5b40b43df54af4197a3aa5b4bc492486010b52010c74e2490d3f4bba7a2f16f027ad8147c733bb9cfd52b6bd9",
          "sha256": "d7f0e883aa73f07be42749ddc1c065662111388614ea7cb549c8c66cabd03409",
          "sha1": "addc9ee356dcff158d83c682268f8c4a4feb368c",
          "md5": "ed20029fa3b25c813bba3d8f8b804b60"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.0-beta.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-alpha04"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-billing-2.7.0-beta.3.aar",
          "url": "notificare-billing-2.7.0-beta.3.aar",
          "size": 28572,
          "sha512": "256657b1a9f6b1aca7e367ee481169ca595e41b5b40b43df54af4197a3aa5b4bc492486010b52010c74e2490d3f4bba7a2f16f027ad8147c733bb9cfd52b6bd9",
          "sha256": "d7f0e883aa73f07be42749ddc1c065662111388614ea7cb549c8c66cabd03409",
          "sha1": "addc9ee356dcff158d83c682268f8c4a4feb368c",
          "md5": "ed20029fa3b25c813bba3d8f8b804b60"
        }
      ]
    }
  ]
}
