{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-scannable",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision",
          "version": {
            "requires": "20.1.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-2.7.2.aar",
          "url": "notificare-scannable-2.7.2.aar",
          "size": 24577,
          "sha512": "4aaff2653473bf47c7d3f2eaf14a51dc778431b93f70f24cd7c102a7d9e41dc86602894a8825c95dd5840f6265116f9572dbb97d49c82efe7f393b3d108a5a8b",
          "sha256": "24efd9469e766bd5693ce05c997623b182899f29fc67cdcc0ae81a957a247f65",
          "sha1": "f7fc62d9d74318cb67e4766d4a78a363f8f290b2",
          "md5": "550c655c86d759a572a11fd9fa5a02d9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-vision",
          "version": {
            "requires": "20.1.3"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-scannable-2.7.2.aar",
          "url": "notificare-scannable-2.7.2.aar",
          "size": 24577,
          "sha512": "4aaff2653473bf47c7d3f2eaf14a51dc778431b93f70f24cd7c102a7d9e41dc86602894a8825c95dd5840f6265116f9572dbb97d49c82efe7f393b3d108a5a8b",
          "sha256": "24efd9469e766bd5693ce05c997623b182899f29fc67cdcc0ae81a957a247f65",
          "sha1": "f7fc62d9d74318cb67e4766d4a78a363f8f290b2",
          "md5": "550c655c86d759a572a11fd9fa5a02d9"
        }
      ]
    }
  ]
}
