{
  "formatVersion": "1.1",
  "component": {
    "group": "re.notifica",
    "module": "notificare-core-hms",
    "version": "2.5.0-beta-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7uk4nzyzwvgqbptkullobh7ley"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.0-beta-1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "5.0.3.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.5.0-beta-1.aar",
          "url": "notificare-core-hms-2.5.0-beta-1.aar",
          "size": 33533,
          "sha512": "6bb9d29209241f0735bdc6cf22d3e8291bfa18bdba0cab3ffa91c83d0d3a5b0cfae0931a2ab9a9b9e3357646d309452a02f05b769c7df6d18d2036a12c35f42f",
          "sha256": "1c52dcb7e0bc1520d8ca836effbeaff1dce816b9a1de3e269da2987668f2797b",
          "sha1": "22f302d1570d7909b0f87bdbef91409993a62722",
          "md5": "639bf7ad1c6ec73ca597758b57ea6488"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "re.notifica",
          "module": "notificare-common",
          "version": {
            "requires": "2.5.0-beta-1"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "push",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "maps",
          "version": {
            "requires": "5.0.3.301"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "org.apache.httpcomponents",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "notificare-core-hms-2.5.0-beta-1.aar",
          "url": "notificare-core-hms-2.5.0-beta-1.aar",
          "size": 33533,
          "sha512": "6bb9d29209241f0735bdc6cf22d3e8291bfa18bdba0cab3ffa91c83d0d3a5b0cfae0931a2ab9a9b9e3357646d309452a02f05b769c7df6d18d2036a12c35f42f",
          "sha256": "1c52dcb7e0bc1520d8ca836effbeaff1dce816b9a1de3e269da2987668f2797b",
          "sha1": "22f302d1570d7909b0f87bdbef91409993a62722",
          "md5": "639bf7ad1c6ec73ca597758b57ea6488"
        }
      ]
    }
  ]
}
